// Code generated by mockery v1.0.0
package mocks

import errors "github.com/stone-payments/goclienttools/errors"
import http "github.com/stone-payments/goclienttools/http"
import mock "github.com/stretchr/testify/mock"

// Interceptor is an autogenerated mock type for the Interceptor type
type Interceptor struct {
	mock.Mock
}

// OnRequest provides a mock function with given fields: _a0
func (_m *Interceptor) OnRequest(_a0 http.RequestOptions) http.RequestOptions {
	ret := _m.Called(_a0)

	var r0 http.RequestOptions
	if rf, ok := ret.Get(0).(func(http.RequestOptions) http.RequestOptions); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.RequestOptions)
		}
	}

	return r0
}

// OnResponse provides a mock function with given fields: _a0
func (_m *Interceptor) OnResponse(_a0 http.Response) (http.Response, errors.Error) {
	ret := _m.Called(_a0)

	var r0 http.Response
	if rf, ok := ret.Get(0).(func(http.Response) http.Response); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.Response)
		}
	}

	var r1 errors.Error
	if rf, ok := ret.Get(1).(func(http.Response) errors.Error); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errors.Error)
		}
	}

	return r0, r1
}
