// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"

// Request is an autogenerated mock type for the Request type
type Request struct {
	mock.Mock
}

// Headers provides a mock function with given fields:
func (_m *Request) Headers() map[string]string {
	ret := _m.Called()

	var r0 map[string]string
	if rf, ok := ret.Get(0).(func() map[string]string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	return r0
}

// JSON provides a mock function with given fields:
func (_m *Request) JSON() interface{} {
	ret := _m.Called()

	var r0 interface{}
	if rf, ok := ret.Get(0).(func() interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}

// Params provides a mock function with given fields:
func (_m *Request) Params() map[string]string {
	ret := _m.Called()

	var r0 map[string]string
	if rf, ok := ret.Get(0).(func() map[string]string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	return r0
}

// SetHeaders provides a mock function with given fields: _a0
func (_m *Request) SetHeaders(_a0 map[string]string) {
	_m.Called(_a0)
}

// SetJSON provides a mock function with given fields: _a0
func (_m *Request) SetJSON(_a0 interface{}) {
	_m.Called(_a0)
}

// SetParams provides a mock function with given fields: _a0
func (_m *Request) SetParams(_a0 map[string]string) {
	_m.Called(_a0)
}
